title: Sophia Deng
author: 
show_excerpts: false

# Minima date format
# Social links in Footer 
minima:
  date_format: "%B %Y"
  social_links:
    twitter: sophdeng
    linkedin: sophdeng

# Header 
header_pages:
- about.md
- writing.md

# Build settings
theme: minima
