title: Sophia Deng
author: 
show_excerpts: false
description: 
- [Twitter][twitter]
- [Linkedin][linkedin]

# Minima date format
# refer to https://shopify.github.io/liquid/filters/date/ if you want to customize this
minima:
  date_format: "%b %-d, %Y"

  # generate social links in footer
  # social_links:
    # twitter: sophdeng
    # linkedin:  soph-deng

# Header 
header_pages:
- about.md
#- writing.md

# Build settings
theme: minima

[linkedin]: https://www.linkedin.com/in/soph-deng/
[twitter]: https://twitter.com/sophdeng
