title: Sophia Deng
author: 
show_excerpts: false
description: 
<a href="https://twitter.com/sophdeng">Twitter</a><br>
<a href="https://www.linkedin.com/in/soph-deng/">LinkedIn</a>


# Minima date format
# refer to https://shopify.github.io/liquid/filters/date/ if you want to customize this
minima:
  date_format: "%b %-d, %Y"

  # generate social links in footer
  # social_links:
    # twitter: sophdeng
    # linkedin:  soph-deng

# Header 
header_pages:
- about.md
#- writing.md

# Build settings
theme: minima
