title: Sophia Deng
author: 
show_excerpts: false

# Minima date format
minima:
  date_format: "%B %Y"

# Header 
header_pages:
- about.md
- writing.md

# Social links in Footer 
  social_links:
    twitter: sophdeng
    linkedin: sophdeng

# Build settings
theme: minima
