title: Sophia Deng
author:
  name: 
  email: 
show_excerpts: false

# Minima date format
minima:
  date_format: "%B %Y"

# Header 
header_pages:
- about.md
- writing.md

# Build settings
theme: minima
