title: Sophia Deng
author: 
show_excerpts: false
title_list: 
description: 
  Testing this section out 

# Minima date format
# Social links in Footer 
minima:
  date_format: "%B %Y"
  social_links:
    twitter: sophdeng
    linkedin: soph-deng

# Header 
header_pages:
- about.md
#- writing.md

# Build settings
theme: minima
